
# Para criar um Usuario
POST http://localhost:3000/users/register
content-type: application/json

{
    "username": "19234439-GNT",
    "password": "COLORDEfwrgtg"
}
### Para fazer login
POST http://localhost:3000/users/login
content-type: application/json

{
     "username": "19234439-GNT",
    "password": "COLORDEfwrgtg"
}

###
#Para adicionar um setor ao Usuario

POST http://localhost:3000/setores
content-type: application/json

{
  "name": "PEDIATRIA",
  "userId": 2  
}

###Para fazer o get de setores associadoados a o seu uruario
GET http://localhost:3000/setores/2







###


# criar leito
# autenticaçao 
# conectar todos sistma e hospodear
# comprar o dominio
# criar a api fake no supabase para fazer requisiçao do hospital fake